# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
language: R
sudo: required
cache: packages
warnings_are_errors: false

befor_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get -qq update
  - sudo apt-get install saga -y
  